// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemperatureService2.Data;

namespace TemperatureService2.Migrations
{
    [DbContext(typeof(SensorsDbContext))]
    partial class SensorsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TemperatureService2.Models.Sensor", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("InternalId");

                    b.Property<int>("Type");

                    b.HasKey("Name");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("TemperatureService2.Models.SensorValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Data");

                    b.Property<string>("SensorName");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("SensorName");

                    b.ToTable("SensorValues");
                });

            modelBuilder.Entity("TemperatureService2.Models.SensorValue", b =>
                {
                    b.HasOne("TemperatureService2.Models.Sensor", "Sensor")
                        .WithMany("Values")
                        .HasForeignKey("SensorName");
                });
#pragma warning restore 612, 618
        }
    }
}
